#!/bin/sh
set -e

[ -d /dev/net ] ||
    mkdir -p /dev/net
[ -c /dev/net/tun ] ||
    mknod /dev/net/tun c 10 200

touch /var/log/pritunl.log
touch /var/run/pritunl.pid
/bin/rm /var/run/pritunl.pid

# if the cmd is bash, just start an interactive shell
if [ "$1" = "bash" ]; then
    exec "$@"
    exit $?
fi

# debug level defaults to false
if [ -z "$DEBUG" ]; then
    DEBUG="false"
fi

## start a local mongodb instance if no mongodb specified through env
if [ -z "$MONGODB_URI" ]; then
  /usr/bin/mongod -f /etc/mongod.conf &
  MONGODB_URI="mongodb://localhost:27017/pritunl"
fi

cat << EOF > /etc/pritunl.conf
{
    "mongodb_uri": "$MONGODB_URI",
    "server_key_path": "/var/lib/pritunl/pritunl.key",
    "log_path": "/var/log/pritunl.log",
    "static_cache": true,
    "server_cert_path": "/var/lib/pritunl/pritunl.crt",
    "temp_path": "/tmp/pritunl_%r",
    "bind_addr": "0.0.0.0",
    "debug": $DEBUG,
    "www_path": "/usr/share/pritunl/www",
    "local_address_interface": "auto",
    "port": 9700
}
EOF

exec /usr/bin/pritunl start
